### ISSUE TITLE
NMS.GEN.FLW.006 - Modification of FLW address via UI or CSV upload

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#106]
The NMS system shall provide means to modify the address/location of a FLW using CSV upload or MDS UI.

The language mapping for the FLW does not change due to change in location information.

**Comment by frankhuster** [comment]
FLWs don't have addresses, the only location information I see is `FrontLineWorker.District`. And so I will assume that this is what this issue is about.

**Comment by frankhuster** [comment]
Hmm, just read what @larubbio & @llavoie wrote in #104 - now slightly confused. 
Additionally, @llavoie's [sample data](https://gist.github.com/llavoie/fbe2106baed00746ec8e) show location information all the way down to village level.
I also notice that @kamknitt's [latest pull request](https://github.com/motech-implementations/mim/pull/295/files#diff-d2bcc04375b3287231a078e60044462cR29) deals with district level location data only.
So what's the deal?

**Comment by llavoie** [comment]
We will have to add additional location fields, based on the reporting
requirements. Rob has proposed that we only save the most granular data
that we have on the record (e.g. if we have Village, we don't save
District, etc.)

You might not want to play around with Location code too much right now
because Rob is reworking it.

On Thu, Jun 4, 2015 at 3:41 PM, Frank Huster <notifications@github.com>
wrote:

> Hmm, just read what @larubbio <https://github.com/larubbio> & @llavoie
> <https://github.com/llavoie> wrote in #104
> <https://github.com/motech-implementations/mim/issues/104> - now slightly
> confused.
> Additionally, @llavoie <https://github.com/llavoie>'s sample data
> <https://gist.github.com/llavoie/fbe2106baed00746ec8e> show location
> information all the way down to village level.
> I also notice that @kamknitt <https://github.com/kamknitt>'s latest pull
> request
> <https://github.com/motech-implementations/mim/pull/295/files#diff-d2bcc04375b3287231a078e60044462cR29>
> deals with district level location data only.
> So what's the deal?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/issues/106#issuecomment-109074511>
> .
>



-- 
Lauren Lavoie
Software Development Manager, Mobile Health Innovations
Grameen Foundation
2101 4th Ave | Suite 1550 | Seattle, WA 98121
206-325-6690 ext 254
llavoie@grameenfoundation.org | Skype:laurenlavoie
Facebook <http://www.facebook.com/StopPovertyNow>│Twitter
<http://twitter.com/grameenfdn>│YouTube
<http://www.youtube.com/user/grameen?blend=6&ob=5> | www.motechsuite.org
*Connecting the World's Poor to Their Potential*

**Comment by larubbio** [comment]
This one should be ok to implement now.  As part of the implementation this should allow initial import to come in at a level lower than district

**Comment by larubbio** [comment]
This will be implemented as part of #104
