### ISSUE TITLE
NMS.GEN.MCTS.004 - MCTS Beneficiary (Kilkari subscriber) identification

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#112]
A Kilkari Beneficiary shall be identified by a unique identifier that comprises of state specific MCTS Id along with State identifier. However, if the Kilkari subscriber activates their subscription by calling the IVR long codes (one for each pack) then they will remain anonymous unless and until MCTS data is uploaded where a pregnancy or birth record matches with the MSISDN number of the anonymous subscriber. For anonymous subscribers, they are only identified by their MSISDN + pack info.

It’s possible that a child MCTS record and pregnancy MCTS record could exist at the same time for the same woman. If the pregnancy record is present, then this record will be UPDATED if a new MCTS record is uploaded  that contains both a child MCTS ID and a pregnancy MCTS ID, where the pregnancy MCTS ID already exists in NMS. In other words, only one subscription will be maintained for the same woman, the pregnancy pack shall be de-activated (if activated) and child-pack shall be activated based on DOB of the child. If, when a MCTS child record is being uploaded, no pregnancy record is found then only the child-pack shall be activated based on DOB of the child. 

For details see Appendix A

**Comment by llavoie** [comment]
From Appendix A:

- During every pregnancy, a mother is assigned a mother ID which is
generated by MCTS application (MCTS ID for mother) and this ID remains the
same, even after Child Birth. This MCTS ID is a unique 18 digit ID (see format
below)
- After the birth of the child, the child is registered with a new MCTS ID, which
is the child ID (child registration is mapped to the mother MCTS ID)
- There are records in MCTS for the babies who have a child MCTS ID but no
mother MCTS ID as their mothers were not registered during their pregnancy.
- MoHFW is in the process of transitioning MCTS to RCH (however, the MCTS
can be used for current purpose). RCH application shall also have a unique
ID for mothers but it will be a 12 digit ID; furthermore post the transition to
RCH, there shall be mapping between RCH IDs and MCTS IDs
- MCTS Team confirmed that Tamil Nadu, Rajasthan, Gujrat, Tripura,
Chhattisgarh and Karnataka have their own formats for IDs in the MCTS,
which is not 18 digit and varies from state to state. So a strict format for
MCTS may not be assume as of now.
- There shall be a web-service to fetch all new or newly updated records since
last fetch from MCTS. However, this interface is outside the scope of this
document.
- MCTS team confirmed that the application does not have a unique MSISDN
mapping i.e. same MSISDN can be linked with multiple mother records. For
the NMS, one MSISDN can map to two records
- Any field update in records shall come as update in entire record

**Comment by llavoie** [comment]
The second part of this (automatic deactivation of mother pack when child is imported) still needs to be implemented.
