### ISSUE TITLE
NMS.MA.COURSE.004 - Maintain count of course attempts

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#151]
MA service shall maintain count of number of times the course is attempted and also allow the user to reattempt the chapter or restart the whole course from beginning.

There shall be no limitation on number of re-attempts.

**Comment by koshalt** [comment]
The count for the number of times the course is attempted is captured by means of CallDetails where we set the service name.

Every MA service call details request represents 1 access of the course and this requirement is then fulfilled at the course level or at an individual FLW level by writing the appropriate ETL job to filter by service and/or group by FLW id.

The service also does not prevent a user from re-attempting a chapter or a sub-unit since the flow for it is controlled at the ivr level. We define the course structure and let IVR walk through it with the duplicate and non-skippable guarantees. Nothing else to do on the motech side of things.

Marking as resolved.

**Comment by llavoie** [comment]
We realized that our earlier interpretation of this requirement was incorrect -- reopening. @koshalt will fix this based on an existing field in mTraining.

**Comment by koshalt** [comment]
fixed and checked in. The data will be tracked in activity records table of mtraining when a user completes a course (regardless of pass or fail)
