### ISSUE TITLE
NMS.KK.ACCESS.005 - Rules for multiple subscriptions for a single MSISDN

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#158]
Kilkari shall allow subscription of service for different packs on the same MSISDN (via bulk upload of MCTS data or via IVR). 

For same pack, if an old subscription has completed/deactivated, then an additional subscription can be made.

MCTS data records with same MSISDN with one having DOB and other having only LMP shall be allowed to subscribe to different packs.

**Comment by llavoie** [comment]
How do you guys want to handle the case where a user subscribes via IVR to a pack that she already has an active/pending subscription for? Make the API idempotent (i.e. no-op) or return an error?

Section 4.1.2.1 states that if a subscription already exists, then the IVR system will check and won't try to create a subscription, but I imagine that for defense in depth (and in order to allow for the right thing to happen when subscriptions are created through MCTS import), we still want to check for an existing subscription on our end and avoid creating the redundant subscription.

**Comment by larubbio** [comment]
The IVR does have the code to check and play a "you are already subscribed"
message.  I think we want to check so we don't create a duplicate
subscription and then have it be idempotent (i.e. no-op).

There is  the case where I user calls and the ivr calls the get user info
api.  Then an mcts enrollment happens, then ivr calls subscribe.  I don't
think that will ever happen, but handling it isn't a bad thing.

**Comment by llavoie** [comment]
Sounds good.

On Tue, Apr 28, 2015 at 3:09 PM, Rob LaRubbio <notifications@github.com>
wrote:

> The IVR does have the code to check and play a "you are already subscribed"
> message. I think we want to check so we don't create a duplicate
> subscription and then have it be idempotent (i.e. no-op).
>
> There is the case where I user calls and the ivr calls the get user info
> api. Then an mcts enrollment happens, then ivr calls subscribe. I don't
> think that will ever happen, but handling it isn't a bad thing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/issues/158#issuecomment-97241717>
> .
>



-- 
Lauren Lavoie
Software Development Manager, Mobile Health Innovations
Grameen Foundation
2101 4th Ave | Suite 1550 | Seattle, WA 98121
206-325-6690 ext 254
llavoie@grameenfoundation.org | Skype:laurenlavoie
Facebook <http://www.facebook.com/StopPovertyNow>│Twitter
<http://twitter.com/grameenfdn>│YouTube
<http://www.youtube.com/user/grameen?blend=6&ob=5> | www.motechsuite.org
*Connecting the World's Poor to Their Potential*
